"""add session models

Revision ID: d65d6e156417
Revises: fdf6a23d91cf
Create Date: 2026-06-10 10:50:44.301947

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd65d6e156417'
down_revision: str | Sequence[str] | None = 'fdf6a23d91cf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_score', sa.Float(), server_default=sa.text('10.0'), nullable=False),
    sa.Column('context_instructions', sa.Text(), nullable=True),
    sa.Column('model_exam_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'archived', name='session_status', native_enum=False, create_constraint=True), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_sessions_user_id'), 'grading_sessions', ['user_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'error', name='exam_status', native_enum=False, create_constraint=True), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['grading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_session_id'), 'exams', ['session_id'], unique=False)
    op.create_table('session_documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('context', 'model_exam', 'rubric', name='document_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['grading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_documents_session_id'), 'session_documents', ['session_id'], unique=False)
    op.create_table('grading_results',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('rubric_filled', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback_report', sa.Text(), nullable=False),
    sa.Column('transcription', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pipeline_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grading_results')
    op.drop_index(op.f('ix_session_documents_session_id'), table_name='session_documents')
    op.drop_table('session_documents')
    op.drop_index(op.f('ix_exams_session_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_grading_sessions_user_id'), table_name='grading_sessions')
    op.drop_table('grading_sessions')
    # ### end Alembic commands ###
